#include <iostream>

int main() {
  /*
  auto value = ...
  auto& value_reference = ...
  auto* value_pointer = ...
  const auto constant_value = ...
  const auto& constant_value_reference = ...
  const auto* constant_ value_pointer = ...
  auto [valuel, value2, valuen] = ...
  */
  
  std::cout << "auto declarations" << std::endl;
}
